USE db_aa090b_ds7utp;

-- CREATE TABLE USER
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(  
    ID_USER int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(255),
    USER_FIRST_NAME VARCHAR(255),
    USER_LAST_NAME VARCHAR(255)
);

-- CREATE SP INSERT NEW USSER
DROP PROCEDURE IF EXISTS SP_USER_NEW;
CREATE PROCEDURE `SP_USER_NEW`(
    IN VAR_USER_NAME VARCHAR(255),
    IN VAR_USER_FIRST_NAME VARCHAR(255),
    IN VAR_USER_LAST_NAME VARCHAR(255)
)
BEGIN
    DECLARE USER_EXIST INT;
    SET @USER_EXIST = (SELECT COUNT(*) FROM USERS WHERE USER_NAME = UPPER(VAR_USER_NAME));
    IF(@USER_EXIST > 0) THEN
        SELECT 'USUARIO YA EXISTE EN LA BD' AS 'MESSAGE_STATE', '400' AS 'CODE_STATE';
    ELSE
        INSERT INTO USERS(USER_NAME, USER_FIRST_NAME, USER_LAST_NAME) VALUES (UPPER(VAR_USER_NAME), UPPER(VAR_USER_FIRST_NAME), UPPER(VAR_USER_LAST_NAME));
        SELECT 'USUARIO REGISTRADO' AS 'MESSAGE_STATE', '200' AS 'CODE_STATE';
    END IF;
END;

CALL SP_USER_NEW('DMaloney', 'david', 'maloney');

-- CREATE SP GET USERS

CREATE PROCEDURE `SP_USER`()
BEGIN
    SELECT ID_USER, USER_NAME, USER_FIRST_NAME, USER_LAST_NAME FROM USERS;
END;

-- CREAR TABLE Categorie

DROP TABLE IF EXISTS CATEGORIES;
CREATE TABLE CATEGORIES(
    ID_CATEGORIE INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    CAT_NAME VARCHAR(255),
    CAT_COLOR VARCHAR(15)
);

-- CREATE SP INSERT NEW CATEGORIE
DROP PROCEDURE IF EXISTS SP_CATEGORIE_NEW;
CREATE PROCEDURE `SP_CATEGORIE_NEW`(
    IN VAR_CAT_NAME VARCHAR(255),
    IN VAR_CAT_COLOR VARCHAR(15)
)
BEGIN
    DECLARE CAT_EXIST INT;
    SET @CAT_EXIST = (SELECT COUNT(*) FROM CATEGORIES WHERE CAT_NAME = UPPER(VAR_CAT_NAME));
    IF(@CAT_EXIST > 0) THEN
        SELECT 'CATEGORIA YA EXISTE EN LA BD' AS 'MESSAGE_STATE', '400' AS 'CODE_STATE';
    ELSE
        INSERT INTO CATEGORIES(CAT_NAME, CAT_COLOR) VALUES (UPPER(VAR_CAT_NAME), UPPER(VAR_CAT_COLOR));
        SELECT 'CATEGORIA REGISTRADA' AS 'MESSAGE_STATE', '200' AS 'CODE_STATE';
    END IF;
END;

CALL SP_CATEGORIE_NEW('CATEGORIA 1', 'Ff0000');

-- CREATE SP GET CATEGORIES
CREATE PROCEDURE `SP_CATEGORIE`()
BEGIN
    SELECT ID_CATEGORIE, CAT_NAME, CAT_COLOR FROM CATEGORIES;
END;

CALL SP_CATEGORIE();