USE db_aa090b_ds7utp;

-- CREATE TABLE USER
DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS(  
    ID_USER int NOT NULL PRIMARY KEY AUTO_INCREMENT,
    USER_NAME VARCHAR(255),
    USER_FIRST_NAME VARCHAR(255),
    USER_LAST_NAME VARCHAR(255)
);

-- CREATE SP INSERT NEW USSER
DROP PROCEDURE IF EXISTS SP_USER_NEW;
CREATE PROCEDURE `SP_USER_NEW`(
    IN VAR_USER_NAME VARCHAR(255),
    IN VAR_USER_FIRST_NAME VARCHAR(255),
    IN VAR_USER_LAST_NAME VARCHAR(255)
)
BEGIN
    DECLARE USER_EXIST INT;
    SET @USER_EXIST = (SELECT COUNT(*) FROM USERS WHERE USER_NAME = UPPER(VAR_USER_NAME));
    IF(@USER_EXIST > 0) THEN
        SELECT 'USUARIO YA EXISTE EN LA BD' AS 'MESSAGE_STATE', '400' AS 'CODE_STATE';
    ELSE
        INSERT INTO USERS(USER_NAME, USER_FIRST_NAME, USER_LAST_NAME) VALUES (UPPER(VAR_USER_NAME), UPPER(VAR_USER_FIRST_NAME), UPPER(VAR_USER_LAST_NAME));
        SELECT 'USUARIO REGISTRADO' AS 'MESSAGE_STATE', '200' AS 'CODE_STATE';
    END IF;
END;

CALL SP_USER_NEW('DMaloney', 'david', 'maloney');

-- CREATE SP GET USERS

CREATE PROCEDURE `SP_USER`()
BEGIN
    SELECT ID_USER, USER_NAME, USER_FIRST_NAME, USER_LAST_NAME FROM USERS;
END;
